//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Xamarin.Forms.Xaml.XamlResourceIdAttribute("APLICACIONCV.Layouts.GridLayout.xaml", "Layouts/GridLayout.xaml", typeof(global::APLICACIONCV.Layouts.GridLayout))]

namespace APLICACIONCV.Layouts {
    
    
    [global::Xamarin.Forms.Xaml.XamlFilePathAttribute("Layouts\\GridLayout.xaml")]
    public partial class GridLayout : global::Xamarin.Forms.ContentPage {
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Forms.Build.Tasks.XamlG", "2.0.0.0")]
        private void InitializeComponent() {
            global::Xamarin.Forms.Xaml.Extensions.LoadFromXaml(this, typeof(GridLayout));
        }
    }
}
